// RootLayout.tsx

import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/component/navbar/page";
import Footer from "@/component/footer/page";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hùngg blogs web",
  description: "Generated by create next app",
};

// props full-layout
type RootLayoutProps = {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="full-layout">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
